config/routes.rb
Rails.application.routes.draw do
 
  root 'patients#index'

  resources :patients
  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor, optional: true
  belongs_to :patient, optional: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy 
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy 
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :set_doctor
  before_action :set_patient, only: [:new, :create]

  def index
    @appointments = @doctor.appointments.order(:date, :time)
  end

  def new
    @patients = Patient.all
    @appointment = @doctor.appointments.new
  end


  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else
      render :new
    end
  end

  def destroy
    @doctor.appointments.find(params[:id]).destroy
    redirect_to doctor_appointments_path (@doctor)
  end
    

  private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :time, :patient_id)
  end

  def set_patient
    @patient = Patient.all - @doctor.patients
  end
 
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  before_action :set_doctor, only: [:show, :destroy] 

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.create(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render :new
  end
end

def destroy
  @doctor.destroy
  redirect_to doctors_path
end

private
def set_doctor
  @doctor = Doctor.find(params[:id])
end

def doctor_params
  params.require(:doctor).permit(:name)
end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  before_action :set_patient, only: [:show, :destroy]
  
  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else 
      render :new
    end
  end

  def destroy
    @patient.destroy 
    redirect_to patients_path
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1><%= @doctor.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor), class: "ui button blue" %>
<hr />

<h2>Appointment Info </h2>
<ul>
  <% @doctor.appointments.each do |appointment| %>
    <li>
      <%= appointment.patient.full_name %>
      <%= appointment.date %>
      <%= appointment.time %>
      <br />
      <%= link_to 'Remove', doctor_appointment_path(@doctor, appointment), method: :delete %>
    </li>
  <% end %>
 

app/views/appointments/new.html.erb
<h1>Add Appointment</h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patients.collect { |p| [p.full_name, p.id] } %>
  <br />
  <%= f.label :date %>
  <%= f.text_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.text_field :time %>
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/doctors/index.html.erb
<h1>Doctor</h1>
<hr />
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2> 

<% @doctors.each do |doctor| %>
 
  <h3><%= link_to doctor.name, doctor %><h2>
    <h4>Number of Patients</h4><%= doctor.patients.count %>
 
  <% end %>
  <br />
  <br />
  <%= link_to 'Add Doctor', new_doctor_path, class: "ui button blue" %>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
  </div>
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', doctor_appointments_path(@doctor), class: "ui blue button" %>
<br />
<br />
<br />
<%= link_to "Delete Doctor", @doctor, method: :delete, class: "ui blue button" %>

app/views/layouts/_navbar.html.erb
<div class="ui menu">
  <%= link_to "Doctors", doctors_path, class: "item" %>
  <%= link_to "Add Doctor", new_doctor_path, class: "item" %>
  <%= link_to "Patients", patients_path, class: "item" %>
  <%= link_to "Add Patient", new_patient_path, class: "item" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>
<hr />
<ul>
<% @patients.each do |patient| %>
  <li>
  <h3><%= link_to patient.full_name, patient %></h3>
  </li>
  <% end %>
  <br />
  <br />
  <%= link_to 'Add Patient', new_patient_path, class: "ui blue button" %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @patient.doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete Patient', @patient, method: :delete, class: "ui blue button" %>
<%= link_to 'Back', patients_path, class: "ui yellow button" %>